# Generated by Django 2.2.6 on 2019-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=12)),
                ('amount', models.CharField(max_length=200)),
                ('external_id', models.CharField(max_length=50)),
                ('payee_note', models.TextField()),
                ('payee_message', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('transaction_ref', models.TextField()),
                ('request_status', models.CharField(max_length=10)),
            ],
        ),
    ]
