# Generated by Django 2.2.6 on 2019-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_momo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='momorequest',
            name='lastest_api_response',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
